global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - '/mnt/c/Users/hana/Desktop/4TWIN/S2/SmartPoperty/smart-property-backend/alert-rules.yml'

scrape_configs:
  - job_name: 'nestjs-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.240.130:30080']
