import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export enum RentalDocumentType {
  CONTRACT = 'contract', // Contract / Contrat
  INVENTORY = 'inventory', // Move-in/out checklist with photos / Inventaire d'état des lieux avec photos
  INSURANCE = 'insurance', // Insurance documents / Documents d'assurance
  INSPECTION = 'inspection', // Post-rental inspection report / Rapport d'inspection après location
  RECEIPT = 'receipt', // Payment receipts / Reçus de paiement
  INVOICE = 'invoice', // Invoices (maintenance, repairs) / Factures (entretien, réparations)
  UTILITY = 'utility', // Utility bills, proof of payment / Factures de services publics, preuve de paiement

  // Identity & Legal Documents
  CIN = 'cin', // Carte d'Identité Nationale / National ID
  PASSPORT = 'passport', // Passport / Passeport
  RESIDENCE_PERMIT = 'residence_permit', // Residence permit / Titre de séjour
  DRIVER_LICENSE = 'driver_license', // Driver's license / Permis de conduire

  // Financial & Banking
  BANK_STATEMENT = 'bank_statement', // Bank statement / Relevé bancaire
  PAYSLIP = 'payslip', // Proof of income / Bulletin de salaire (preuve de revenu)
  TAX_RETURN = 'tax_return', // Tax return / Déclaration de revenus
  GUARANTOR_PROOF = 'guarantor_proof', // Guarantor income/ID docs / Preuves d'identité/revenu du garant
  DEPOSIT_PROOF = 'deposit_proof', // Security deposit payment proof / Preuve de paiement du dépôt de garantie
  STANDING_ORDER = 'standing_order', // Automatic payment mandate / Ordre permanent / mandat de paiement automatique

  // Property Legal
  PROPERTY_TITLE = 'property_title', // Proof of ownership / Titre de propriété
  LAND_REGISTRY = 'land_registry', // Land registry extract / Extrait du registre foncier
  CO_OWNERSHIP_RULES = 'co_ownership_rules', // Condo/building regulations / Règlement de copropriété / règles de l'immeuble

  // Tenant History
  PREVIOUS_CONTRACT = 'previous_contract', // Previous rental reference / Contrat de location précédent (référence)
  LANDLORD_REFERENCE = 'landlord_reference', // Landlord reference / Référence du précédent propriétaire/gestionnaire
  EMPLOYMENT_CONTRACT = 'employment_contract', // Employment contract / Contrat de travail

  // Compliance & Safety
  EPC = 'epc', // Energy Performance Certificate / Certificat de performance énergétique
  GAS_SAFETY = 'gas_safety', // Gas safety certificate / Certificat de sécurité gaz
  ELECTRICAL_SAFETY = 'electrical_safety', // Electrical safety certificate / Certificat de sécurité électrique
  ASBESTOS_REPORT = 'asbestos_report', // Asbestos report / Rapport d'amiante
  LEAD_REPORT = 'lead_report', // Lead paint report / Rapport de peinture au plomb

  OTHER = 'other', // Other / Autre
}

export type RentalDocumentDocument = RentalDocument & Document;

@Schema({ timestamps: true, collection: 'rental_documents' })
export class RentalDocument {
  @Prop({ type: Types.ObjectId, ref: 'Rental', required: true, index: true })
  rentalId!: Types.ObjectId;

  @Prop({ enum: RentalDocumentType, required: true })
  documentType!: RentalDocumentType;

  // ─── Document Info ────────────────────────────────────────────
  @Prop({ required: true })
  title!: string;

  @Prop()
  description?: string;

  @Prop({ required: true })
  documentUrl!: string; // Cloudinary URL

  @Prop()
  publicId?: string; // Cloudinary public ID

  @Prop()
  fileName?: string;

  @Prop({ default: 'application/pdf' })
  mimeType?: string;

  @Prop({ min: 0 })
  sizeKb?: number;

  // ─── Access Control ───────────────────────────────────────────
  @Prop({ default: true })
  isPublic?: boolean; // Can tenant see it?

  @Prop({ type: [Types.ObjectId], ref: 'User', default: [] })
  visibleTo?: Types.ObjectId[]; // Explicit access list (if not public)

  // ─── Expiry & Retention ───────────────────────────────────────
  @Prop()
  expiresAt?: Date; // For time-sensitive docs (e.g., insurance)

  @Prop({ default: false })
  isArchived?: boolean;

  @Prop()
  archivedAt?: Date;

  // ─── Upload Info ───────────────────────────────────────────────
  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  uploadedBy!: Types.ObjectId;

  @Prop()
  uploadedAt?: Date;

  // ─── Metadata ───────────────────────────────────────────────────
  @Prop()
  notes?: string;

  // ─── Soft Delete ───────────────────────────────────────────────
  @Prop({ default: false })
  isDeleted?: boolean;

  @Prop()
  deletedAt?: Date;

  // ─── Timestamps (auto-generated by Mongoose) ───────────────────────
  @Prop()
  createdAt?: Date;

  @Prop()
  updatedAt?: Date;
}

export const RentalDocumentSchema =
  SchemaFactory.createForClass(RentalDocument);

// Indexes for fast queries
RentalDocumentSchema.index({ rentalId: 1, documentType: 1 });
RentalDocumentSchema.index({ rentalId: 1, isPublic: 1 });
RentalDocumentSchema.index({ uploadedBy: 1, createdAt: -1 });
RentalDocumentSchema.index({ expiresAt: 1 });
RentalDocumentSchema.index({ isArchived: 1, isDeleted: 1 });
