import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type RentalDocument = Rental & Document;

@Schema({ timestamps: true, collection: 'rentals' })
export class Rental {
    @Prop({ type: Types.ObjectId, ref: 'Property', required: true })
    propertyId!: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'PropertyListing', required: true })
    propertyListingId!: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'User', required: true })
    ownerId!: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'User', required: true })
    tenantId!: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'User' })
    agentId?: Types.ObjectId;

    @Prop({ type: String })
    branchId?: string;

    @Prop({ min: 1 })
    durationMonths?: number;

    @Prop({ default: false })
    autoRenew!: boolean;

    @Prop({ min: 0 })
    noticePeriodDays?: number;

    @Prop()
    contractSignedAt?: Date;

    @Prop()
    moveInDate?: Date;

    @Prop()
    moveOutDate?: Date;

    @Prop()
    lastPaymentDate?: Date;

    @Prop()
    nextPaymentDue?: Date;

    @Prop({ min: 0, default: 0 })
    outstandingBalance!: number;

    @Prop({ min: 1, default: 1 })
    paymentFrequencyMonths!: number;

    @Prop({ enum: ['pending', 'rented', 'ended', 'terminated'], default: 'pending' })
    status!: string;  // pending | rented | ended | terminated

    @Prop()
    notes?: string;

    // ─── Timestamps (auto-generated by Mongoose) ───────────────────────
    @Prop()
    createdAt?: Date;

    @Prop()
    updatedAt?: Date;
}

export const RentalSchema = SchemaFactory.createForClass(Rental);

RentalSchema.index({ propertyId: 1, moveOutDate: 1 });
RentalSchema.index({ ownerId: 1, tenantId: 1 });
