import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type RentalContractDocument = RentalContract & Document;

@Schema({ timestamps: true, collection: 'rental_contracts' })
export class RentalContract {
  @Prop({ type: Types.ObjectId, ref: 'Rental', required: true, index: true })
  rentalId!: Types.ObjectId;

  // ─── Document Storage ──────────────────────────────────────────
  @Prop({ required: true })
  documentUrl!: string; // Cloudinary URL to PDF

  @Prop()
  publicId?: string; // Cloudinary public ID (for deletion, update)

  @Prop({ default: 1 })
  version!: number; // Track amendments: v1, v2, v3

  @Prop()
  fileName?: string; // e.g., "rental_agreement_v1.pdf"

  @Prop({ default: 'application/pdf' })
  mimeType?: string;

  @Prop({ min: 0 })
  sizeKb?: number;

  // ─── Signatures ────────────────────────────────────────────────
  @Prop()
  signedAt?: Date;

  @Prop({ type: [Types.ObjectId], ref: 'User', default: [] })
  signedBy?: Types.ObjectId[]; // Users who have signed

  // ─── Tenant Signature ──────────────────────────────────────────
  @Prop()
  tenantSignatureImageUrl?: string;

  @Prop()
  tenantSignatureImagePublicId?: string;

  @Prop()
  tenantSignedAt?: Date;

  // ─── Owner Signature ───────────────────────────────────────────
  @Prop()
  ownerSignatureImageUrl?: string;

  @Prop()
  ownerSignatureImagePublicId?: string;

  @Prop()
  ownerSignedAt?: Date;

  // ─── Agent Signature ───────────────────────────────────────────
  @Prop()
  agentSignatureImageUrl?: string;

  @Prop()
  agentSignatureImagePublicId?: string;

  @Prop()
  agentSignedAt?: Date;

  // ─── Legal Hold & Retention ────────────────────────────────────
  @Prop()
  expiresAt?: Date; // Legal hold expiry: moveOutDate + 7 years (auto-calculated)

  @Prop({ default: false })
  isArchived?: boolean;

  @Prop()
  archivedAt?: Date;

  // ─── Metadata ───────────────────────────────────────────────────
  @Prop()
  notes?: string;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  uploadedBy?: Types.ObjectId; // Who uploaded contract

  // ─── Timestamps (auto-generated by Mongoose) ───────────────────────
  @Prop()
  createdAt?: Date;

  @Prop()
  updatedAt?: Date;
}

export const RentalContractSchema =
  SchemaFactory.createForClass(RentalContract);

// Indexes for fast queries
RentalContractSchema.index({ rentalId: 1 });
RentalContractSchema.index({ version: -1 });
RentalContractSchema.index({ expiresAt: 1 });
RentalContractSchema.index({ isArchived: 1 });
