import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type ApplicationDocument = Application & Document;

export enum ApplicationStatus {
  PENDING = 'PENDING',
  REQUEST_MORE_DOCUMENTS = 'REQUEST_MORE_DOCUMENTS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum RejectionType {
  CAN_REAPPLY = 'CAN_REAPPLY',
  BLOCKED = 'BLOCKED',
}

export enum SolvencyAnalysisStatus {
  NOT_STARTED = 'NOT_STARTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum SolvencyRecommendation {
  APPROVE = 'APPROVE',
  REVIEW = 'REVIEW',
  REJECT = 'REJECT',
}

@Schema({ timestamps: true })
export class Application {
  @Prop({ type: Types.ObjectId, ref: 'Property', required: true })
  propertyId!: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  clientId!: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  agentId!: Types.ObjectId;

  @Prop({ required: true })
  fullName!: string;

  @Prop({ required: true })
  email!: string;

  @Prop({ required: true })
  phone!: string;

  @Prop()
  age?: number;

  @Prop()
  familyMembers?: number;

  @Prop()
  occupation?: string;

  @Prop()
  employmentStatus?: string;

  @Prop()
  employerName?: string;

  @Prop()
  financialSupportDetails?: string;

  @Prop()
  studentCardNumber?: string;

  @Prop()
  monthlyIncome?: number;

  @Prop()
  preferredMoveInDate?: Date;

  @Prop()
  leaseDurationMonths?: number;

  @Prop()
  hasPets?: boolean;

  @Prop()
  petsDetails?: string;

  @Prop()
  hasGuarantor?: boolean;

  @Prop()
  guarantorName?: string;

  @Prop()
  guarantorPhone?: string;

  @Prop()
  notes?: string;

  @Prop()
  documentUrl?: string;

  @Prop({
    default: ApplicationStatus.PENDING,
    enum: Object.values(ApplicationStatus),
  })
  status!: string;

  @Prop({ enum: Object.values(RejectionType), required: false })
  rejectionType?: string;

  @Prop({ required: false })
  rejectionReason?: string;

  @Prop({
    type: String,
    enum: Object.values(SolvencyAnalysisStatus),
    default: SolvencyAnalysisStatus.NOT_STARTED,
  })
  solvencyStatus?: string;

  @Prop({ required: false })
  solvencyLastRunAt?: Date;

  @Prop({ required: false })
  solvencyError?: string;

  @Prop({
    type: {
      provider: { type: String },
      ocrConfidence: { type: Number },
      extractedFullName: { type: String },
      extractedMonthlyIncome: { type: Number },
      declaredMonthlyIncome: { type: Number },
      incomeMismatchPercent: { type: Number },
      nameMatchScore: { type: Number },
      monthlyPropertyCost: { type: Number },
      affordabilityRatio: { type: Number },
      occupationAssessment: {
        type: {
          status: {
            type: String,
            enum: ['VALID', 'SUSPICIOUS', 'MISSING'],
          },
          score: { type: Number },
          reason: { type: String },
          normalizedOccupation: { type: String },
        },
        default: null,
      },
      riskScore: { type: Number },
      recommendation: {
        type: String,
        enum: Object.values(SolvencyRecommendation),
      },
      fraudFlags: { type: [String], default: [] },
      checks: {
        type: [
          {
            name: { type: String, required: true },
            passed: { type: Boolean, required: true },
            expected: { type: String },
            actual: { type: String },
            note: { type: String },
          },
        ],
        default: [],
      },
      summary: { type: String },
      documentTextExcerpt: { type: String },
      analyzedAt: { type: Date },
      modelVersion: { type: String },
    },
    default: null,
  })
  solvencyAnalysis?: any;

  @Prop({ type: [String], default: [] })
  improveChecklist?: string[];

  // ÔöÇÔöÇÔöÇ Timestamps (auto-generated by Mongoose) ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
  @Prop()
  createdAt?: Date;

  @Prop()
  updatedAt?: Date;
}

export const ApplicationSchema = SchemaFactory.createForClass(Application);
