import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type ApplicationDocument = Application & Document;

export enum ApplicationStatus {
  PENDING = 'PENDING',
  REQUEST_MORE_DOCUMENTS = 'REQUEST_MORE_DOCUMENTS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum RejectionType {
  CAN_REAPPLY = 'CAN_REAPPLY',
  BLOCKED = 'BLOCKED',
}

@Schema({ timestamps: true })
export class Application {
  @Prop({ type: Types.ObjectId, ref: 'Property', required: true })
  propertyId!: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  clientId!: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  agentId!: Types.ObjectId;

  @Prop({ required: true })
  fullName!: string;

  @Prop({ required: true })
  email!: string;

  @Prop({ required: true })
  phone!: string;

  @Prop()
  age?: number;

  @Prop()
  familyMembers?: number;

  @Prop()
  occupation?: string;

  @Prop()
  monthlyIncome?: number;

  @Prop()
  notes?: string;

  @Prop()
  documentUrl?: string;

  @Prop({ default: ApplicationStatus.PENDING, enum: Object.values(ApplicationStatus) })
  status!: string;

  @Prop({ enum: Object.values(RejectionType), required: false })
  rejectionType?: string;

  @Prop({ required: false })
  rejectionReason?: string;

  @Prop({ type: [String], default: [] })
  improveChecklist?: string[];

  // ─── Timestamps (auto-generated by Mongoose) ───────────────────────
  @Prop()
  createdAt?: Date;

  @Prop()
  updatedAt?: Date;
}

export const ApplicationSchema = SchemaFactory.createForClass(Application);
