apiVersion: v1
kind: Service
metadata:
  name: smart-property-backend
  namespace: default
spec:
  selector:
    app: smart-property-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort